name: Build Solana Program

on:
  workflow_dispatch:
  push:
    paths:
      - 'contracts/**'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  build-program:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          source $HOME/.cargo/env
          solana --version
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Install BPF tools
        run: |
          rustup target add bpfel-unknown-unknown
          # Install Solana BPF dependencies directly
          (cd && pwd && curl -L https://github.com/solana-labs/bpf-tools/releases/download/v1.32/bpf-tools-linux.tar.bz2 | tar jxf -)
          echo "$(cd && pwd)/bpf-tools/llvm/bin" >> $GITHUB_PATH
          echo "$(cd && pwd)/bpf-tools/rust/bin" >> $GITHUB_PATH

      - name: Build BuddyFi Program
        run: |
          cd contracts/buddyfi-program
          cargo build-bpf
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: program-artifacts
          path: contracts/buddyfi-program/target/deploy/