name: Build Solana Program

on:
  workflow_dispatch:
  push:
    paths:
      - 'contracts/**'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  build-program:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Setup Rust and BPF toolchain
        run: |
          # Install the Rust toolchain that Solana expects
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          
          # Let Solana install the specific compatible toolchain with BPF support
          ~/.local/share/solana/install/active_release/bin/solana-install init
          
          # Verify installations
          solana --version
          rustc --version
          
          # Explicitly add the BPF target
          rustup target add bpfel-unknown-unknown

      - name: Build BuddyFi Program
        run: |
          cd contracts/buddyfi-program
          cargo build-bpf
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: program-artifacts
          path: contracts/buddyfi-program/target/deploy/