name: Build Solana Program

on:
  workflow_dispatch:
  push:
    paths:
      - 'contracts/**'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  build-program:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Install Solana CLI
        run: |
          # Install Solana CLI
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
          # Make sure the binary is accessible in this step
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          # Verify installation
          solana --version
          # Make path available to subsequent steps
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Add BPF target
        run: |
          rustup target add bpfel-unknown-unknown
          # Verify Solana CLI is available
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Build BuddyFi Program
        run: |
          cd contracts/buddyfi-program
          # Use full path to solana
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          cargo build-bpf
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: program-artifacts
          path: contracts/buddyfi-program/target/deploy/