name: Build Solana Program

on:
  workflow_dispatch:
  push:
    paths:
      - 'contracts/**'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  build-program:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          solana --version
      
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-10
          override: true
      
      - name: Add BPF target
        run: |
          rustup target add bpfel-unknown-unknown
      
      - name: Install Solana BPF tools
        run: |
          cargo install solana-sdk-bpf
      
      - name: Build BuddyFi Program
        run: |
          cd contracts/buddyfi-program
          cargo build-bpf
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-artifacts
          path: contracts/buddyfi-program/target/deploy/