name: Build WebApp

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/web/**'  # Only trigger for changes in the webapp folder
  pull_request:
    paths:
      - 'apps/web/**'  # Only trigger for PRs involving the webapp folder

jobs:
  build-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Add steps for building your frontend (e.g., install dependencies, build)
      - name: Install dependencies
        run: |
          npm install

      - name: Build the webapp
        run: |
          npm run build
